# Generated by Django 3.1 on 2020-08-15 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamentName', models.CharField(max_length=50, verbose_name='Департамент')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30, verbose_name='Имя')),
                ('middleName', models.CharField(max_length=30, verbose_name='Отчество')),
                ('lastName', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.departament')),
            ],
        ),
    ]
